name: run unit tests of feature branches

on:
  push:
    branches:
      'features/*'

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2

     - name: run unit test
       uses: mvn test
